// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.2
// source: newsfeed.proto

package newsfeed

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NewsfeedClient is the client API for Newsfeed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsfeedClient interface {
}

type newsfeedClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsfeedClient(cc grpc.ClientConnInterface) NewsfeedClient {
	return &newsfeedClient{cc}
}

// NewsfeedServer is the server API for Newsfeed service.
// All implementations must embed UnimplementedNewsfeedServer
// for forward compatibility
type NewsfeedServer interface {
	mustEmbedUnimplementedNewsfeedServer()
}

// UnimplementedNewsfeedServer must be embedded to have forward compatible implementations.
type UnimplementedNewsfeedServer struct {
}

func (UnimplementedNewsfeedServer) mustEmbedUnimplementedNewsfeedServer() {}

// UnsafeNewsfeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsfeedServer will
// result in compilation errors.
type UnsafeNewsfeedServer interface {
	mustEmbedUnimplementedNewsfeedServer()
}

func RegisterNewsfeedServer(s grpc.ServiceRegistrar, srv NewsfeedServer) {
	s.RegisterService(&Newsfeed_ServiceDesc, srv)
}

// Newsfeed_ServiceDesc is the grpc.ServiceDesc for Newsfeed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Newsfeed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newsfeed.Newsfeed",
	HandlerType: (*NewsfeedServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "newsfeed.proto",
}
